Repository nullgr/instant-validation, pull requests merged in 2019-07, with the labels that each got.

#15 Feature/performance fields loading function fires now only on demand (if fields property is used)
  __tests__/testUtils/testRules.ts
  build/modules/findDifference.js
  build/modules/getErrorMessages.js
  build/modules/getFieldsData.js
  build/modules/showAllErrors.js
  build/modules/validateFieldsByDiff.js
  build/validator.js
  package-lock.json
  src/index.ts
  src/modules/findDifference.ts
  src/modules/getErrorMessages.ts
  src/modules/getFieldsData.ts
  src/modules/showAllErrors.ts
  src/modules/validateFieldsByDiff.ts
  src/validator.ts
Labels: performance

#32 Feature/recipes
  README.md
  docs/recipes.md
Labels: docs

#41 Added more info about the type of validation result
  __tests__/findDifference.test.ts
  docs/recipes.md
  examples/index.ts
  package.json
  src/validator/index.ts
  src/validator/modules/buildInitialState.ts
  src/validator/modules/findDifference.ts
  src/validator/modules/getErrorMessages.ts
  src/validator/modules/getFieldsData.ts
  src/validator/modules/isStateValid.ts
  src/validator/modules/showAllErrors.ts
  src/validator/modules/validateFieldsByDiff.ts
  src/validator/types.d.ts
  src/validator/validator.ts
Labels: enhancement

#42 [Version] 1.0.1 fix and improve typings, improve .npmigonre
  .npmignore
  __tests__/testUtils/index.js
  examples/index.ts
  global.d.ts
  package-lock.json
  package.json
  src/validator/types.ts
  src/validator/validator.ts
Labels: bug, enhancement
